// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: prime.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace PrimeAPI {
  public static partial class PrimeService
  {
    static readonly string __ServiceName = "PrimeAPI.PrimeService";

    static readonly grpc::Marshaller<global::PrimeAPI.PrimeRequest> __Marshaller_PrimeAPI_PrimeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PrimeAPI.PrimeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::PrimeAPI.PrimeResponse> __Marshaller_PrimeAPI_PrimeResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PrimeAPI.PrimeResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::PrimeAPI.PrimeRequest, global::PrimeAPI.PrimeResponse> __Method_Decompose = new grpc::Method<global::PrimeAPI.PrimeRequest, global::PrimeAPI.PrimeResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Decompose",
        __Marshaller_PrimeAPI_PrimeRequest,
        __Marshaller_PrimeAPI_PrimeResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::PrimeAPI.PrimeReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PrimeService</summary>
    [grpc::BindServiceMethod(typeof(PrimeService), "BindService")]
    public abstract partial class PrimeServiceBase
    {
      public virtual global::System.Threading.Tasks.Task Decompose(global::PrimeAPI.PrimeRequest request, grpc::IServerStreamWriter<global::PrimeAPI.PrimeResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PrimeService</summary>
    public partial class PrimeServiceClient : grpc::ClientBase<PrimeServiceClient>
    {
      /// <summary>Creates a new client for PrimeService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PrimeServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PrimeService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PrimeServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PrimeServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PrimeServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::PrimeAPI.PrimeResponse> Decompose(global::PrimeAPI.PrimeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Decompose(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::PrimeAPI.PrimeResponse> Decompose(global::PrimeAPI.PrimeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Decompose, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PrimeServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PrimeServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PrimeServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Decompose, serviceImpl.Decompose).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PrimeServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Decompose, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::PrimeAPI.PrimeRequest, global::PrimeAPI.PrimeResponse>(serviceImpl.Decompose));
    }

  }
}
#endregion
