// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: average.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace AverageAPI {
  public static partial class AverageService
  {
    static readonly string __ServiceName = "AverageAPI.AverageService";

    static readonly grpc::Marshaller<global::AverageAPI.AverageRequest> __Marshaller_AverageAPI_AverageRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AverageAPI.AverageRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::AverageAPI.AverageResponse> __Marshaller_AverageAPI_AverageResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AverageAPI.AverageResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::AverageAPI.AverageRequest, global::AverageAPI.AverageResponse> __Method_ComputeAverage = new grpc::Method<global::AverageAPI.AverageRequest, global::AverageAPI.AverageResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "ComputeAverage",
        __Marshaller_AverageAPI_AverageRequest,
        __Marshaller_AverageAPI_AverageResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AverageAPI.AverageReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AverageService</summary>
    [grpc::BindServiceMethod(typeof(AverageService), "BindService")]
    public abstract partial class AverageServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::AverageAPI.AverageResponse> ComputeAverage(grpc::IAsyncStreamReader<global::AverageAPI.AverageRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AverageService</summary>
    public partial class AverageServiceClient : grpc::ClientBase<AverageServiceClient>
    {
      /// <summary>Creates a new client for AverageService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AverageServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AverageService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AverageServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AverageServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AverageServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncClientStreamingCall<global::AverageAPI.AverageRequest, global::AverageAPI.AverageResponse> ComputeAverage(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ComputeAverage(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::AverageAPI.AverageRequest, global::AverageAPI.AverageResponse> ComputeAverage(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_ComputeAverage, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AverageServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AverageServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AverageServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ComputeAverage, serviceImpl.ComputeAverage).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AverageServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ComputeAverage, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::AverageAPI.AverageRequest, global::AverageAPI.AverageResponse>(serviceImpl.ComputeAverage));
    }

  }
}
#endregion
